keys:
  - &admin_cameron_desktop age17zj03m39druezfu6le0ycvasr9thv4y06hdwzegh6rajgwrdhpgqsnwzes
  - &admin_cameron_laptop age1htjdvcdqvwe8rxx23fz2aw97a6c2zxwwu84m25jugh779vqkfg4sg5c83z
  - &gridur age1m0wk3gylpmcl74q0yw38wnvae498yq8a8xs2cd2jwuwfycxp8g9spn7zmq
  - &server_talos age15ygfzth73d2q3dm305qg53x6g9u9knau9fytvnrlut4u0usg5cpqeq4s5g
  - &server_icebox age1lh3vlrqgvde043kxlvyvdt6wlj968a0szm3exwwhsvx04xeh0eushpnp75
  - &server_icebox2 age1dfy9sd98v2h5sh0la45pq4rszl7lag3nwvj5j5exgjh3kk30mgpq9s5h49
  - &laptop_gargantuan age1408qgh9ekswerw33ae2yzmfu8la4kq2szl2rwvslx6cpujsfr58ss6q9tx
creation_rules:
  - path_regex: secrets[^/\\]*\.(yml|yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_cameron_desktop
      - *admin_cameron_laptop
      - *gridur
      - *server_talos
      - *server_icebox
      - *server_icebox2
      - *laptop_gargantuan

  # Possible to specify which masters can access which keys, like this
  # - path_regex: secrets(\\|\/)talos(\\|\/)[^/]+\.(yml|yaml|json|env|ini)$
  #   key_groups:
  #   - age:
  #     - *admin_cameron_desktop
  #     - *admin_cameron_laptop
  #     - *server_talos
  # - path_regex: secrets(\\|\/)gargantuan(\\|\/)[^/]+\.(yml|yaml|json|env|ini)$
  #   key_groups:
  #   - age:
  #     - *admin_cameron_desktop
  #     - *admin_cameron_laptop
