#!/usr/bin/env sh

# cd $HOME/github/nixdots
cd "$(dirname "$0")"
git pull

old=$(readlink /nix/var/nix/profiles/system | awk -F'-' '{print $2}')
echo "---- OLD GENERATION $old ----"

sudo nixos-rebuild --show-trace --option eval-cache false --fast --flake '.#' "$@"

current=$(readlink /nix/var/nix/profiles/system | awk -F'-' '{print $2}')
echo
echo "Generation $old -> $current"
