#!/usr/bin/env sh
set -e

# cd $HOME/github/nixdots
cd "$(dirname "$0")"

if [ $# -eq 0 ]; then
  args="switch"
else
  args="$@"
fi

old=$(readlink /nix/var/nix/profiles/system | awk -F'-' '{print $2}')
echo "---- OLD GENERATION $old ----"
# autocommit, ignore errors
git add . && git commit -m "$(date '+%Y-%m-%d %H:%M:%S %Z') gen $old" || true
# sync up
git pull
git push

sudo nixos-rebuild --flake '.#' "$args" --accept-flake-config --show-trace
# --show-trace --option eval-cache false

current=$(readlink /nix/var/nix/profiles/system | awk -F'-' '{print $2}')
echo
echo "Generation $old -> $current"
