#!/usr/bin/env sh

cd $HOME/github/nixdots
git pull

sudo nixos-rebuild switch --flake '.#talos' --show-trace
generation=$(ls /nix/var/nix/profiles | tail -n 1 | awk -F'-' '{print $2}')

echo
echo "Generation $generation built and switched to!"