#!/usr/bin/env sh

cd $HOME/github/nixdots
git pull

old=$(readlink /nix/var/nix/profiles/system | awk -F'-' '{print $2}')
sudo nixos-rebuild switch --flake '.#talos' --show-trace
current=$(readlink /nix/var/nix/profiles/system | awk -F'-' '{print $2}')

echo
echo "Switch generation $old -> $current"