#!/usr/bin/env sh

# Check if wlogout is already running
if pgrep -x "wlogout" > /dev/null
then
    pkill -x "wlogout"
    exit 0
fi

# detect monitor y res
x_mon=$( cat /sys/class/drm/*/modes | head -1  ) 
y_mon=$( echo $x_mon | cut -d 'x' -f 2 )
x_mon=$( echo $x_mon | cut -d 'x' -f 1 )

# scale config layout and style
wlColms=6
export mgn=$(( y_mon * 28 / 100 ))
export hvr=$(( y_mon * 23 / 100 ))

# scale font size
export fntSize=$(( y_mon * 2 / 100 ))

# detect gtk system theme
export gtkThm=`gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g"`
export csMode=`gsettings get org.gnome.desktop.interface color-scheme | sed "s/'//g" | awk -F '-' '{print $2}'`
export BtnCol=`[ "$csMode" == "dark" ] && ( echo "white" ) || ( echo "black" )`
export wbarTheme="${gtkThm}"

# eval hypr border radius
hyprTheme="$HOME/.config/hypr/hyprland.conf"
hypr_border=`awk -F '=' '{if($1~"rounding") print $2}' $hyprTheme | sed 's/ //g'`
export active_rad=$(( hypr_border * 5 ))
export button_rad=$(( hypr_border * 8 ))

# eval config files
wlStyle=`envsubst < $wlTmplt`

# launch wlogout
wlogout -b $wlColms -c 0 -r 0 -m 0 --layout $wLayout --css <(echo "$wlStyle") --protocol layer-shell

