#!/usr/bin/env sh

sleep 4
killall -e xdg-desktop-portal-wlr
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-gtk
killall xdg-desktop-portal
/nix/store/bgll3z9c0kb44alpq32mn1hkwp9xwjc4-xdg-desktop-portal-hyprland-0.3.1/libexec/xdg-desktop-portal-hyprland &
#/usr/lib/xdg-desktop-portal-hyprland &
sleep 4
#/usr/lib/xdg-desktop-portal &
/nix/store/nm0lvn0bfj7pr2smx6mqs6gqg1bkyxax-xdg-desktop-portal-1.16.0/libexec/xdg-desktop-portal &
