#!/usr/bin/env sh

# Set XDG_PICTURES_DIR if not already
if [ -z "$XDG_SCREENSHOTS_DIR" ] ; then
    XDG_SCREENSHOTS_DIR="$HOME/Pictures/Screenshots"
fi

swpy_dir="$HOME/.config/swappy"
save_dir="${2:-$XDG_SCREENSHOTS_DIR}"
save_file=$(date +'%y%m%d_%Hh%Mm%Ss_screenshot.png')

# Ensure the dir exists
mkdir -p $save_dir

# Entrypoint
case $1 in
p)  grim $save_dir/$save_file ;;
s)  mkdir -p $swpy_dir
    echo -e "[Default]\nsave_dir=$save_dir\nsave_filename_format=$save_file" > $swpy_dir/config
    grim -g "$(slurp)" - | swappy -f - ;;
w)  winPos=$(hyprctl activewindow | awk '/^.at/ {print $2}')
    winSize=$(hyprctl activewindow | awk '/^.size/ {print $2}' | sed 's/,/x/')
    grim -g "$winPos $winSize" $save_dir/$save_file ;;
*)  echo "...valid options are..."
    echo "p : print screen to $save_dir"
    echo "s : snip current screen to $save_dir"   
    exit 1 ;;
esac

# Notify the user that it succeeded
if [ -f "$save_dir/$save_file" ] ; then
    dunstify "Screenshot taken" "$save_file" -a "Dunst" -i "$save_dir/$save_file" -r 91190 -t 4000
fi
